language: python
python:
  - 3.6
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
#      - chromium-chromedriver
install:
  - pip install -r requirements.txt
  - python setup.py develop
before_script:
  - wget "http://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - robot -A tests/conf/default.args tests
